### PR TITLE
p1c2u/openapi-core#296: Adds support for OpenAPI 3.1

### PR DESCRIPTION
**Pull request by nezhar**
This PR is build on top of:

- https://github.com/p1c2u/openapi-schema-validator/pull/18
- https://github.com/p1c2u/openapi-spec-validator/pull/128

Support for Python 3.6 is dropped as in the alpha release of jsonschema.

### CODE REVIEW

**Comment by tschmidtb51** [comment]
@p1c2u Could you please add your review?

**Comment by p1c2u** [comment]
Python 3.6 support drop can be extracted to separate commit/PR

**Comment by p1c2u** [comment]
We need to add information about supported versions and how to use them to the README file

**Comment by nezhar** [comment]
> Python 3.6 support drop can be extracted to separate commit/PR

Moved it to https://github.com/p1c2u/openapi-core/pull/383

**Comment by nezhar** [comment]
This is now using `openapi-schema-validator==0.3.0a1` and `openapi-spec-validator==0.5.0a1`. 

As `openapi_v3_spec_validator` is referencing to `openapi_v31_spec_validator` with the new alpha release, all tests for `3.0` specs need to explicitly define the `spec_validator` in  the `create_spec` function.

Example:
```python
from openapi_spec_validator import openapi_v31_spec_validator

spec = create_spec(
    spec_dict, spec_uri, spec_validator=openapi_v30_spec_validator
)
```

**Comment by nezhar** [comment]
@p1c2u are there any plans to continue with this or is it heading in a wrong direction? I'm asking, because since https://github.com/p1c2u/openapi-core/pull/393 was merged, there are a few things that need to be adapted in the PR.

**Comment by p1c2u** [comment]
Closing in favor of #419

**Pull request closed without merging**
