### PR TITLE
Structured exceptions

### PR DESCRIPTION
**Pull request by domenkozar**
PS: This uses https://github.com/p1c2u/openapi-core/pull/89 as a base just in hope not to have to deal with conflicts twice :)

### CODE REVIEW

**Comment by domenkozar** [comment]
@p1c2u could you help me why these exceptions are left out? https://github.com/p1c2u/openapi-core/blob/master/openapi_core/shortcuts.py#L34

The problem is, they get raised on validation of response.

**Comment by p1c2u** [comment]
@domenkozar it's to filter out body validation errors (OpenAPIRequestBodyError, OpenAPIMediaTypeError, OpenAPISchemaError)

**Comment by domenkozar** [comment]
@p1c2u why does it need to filter out body errors? Those are also part of the schema validation?

**Comment by domenkozar** [comment]
I'm confused about the following:

- `InvalidSchemaValue` (in schema validation) gets caught and reraised as `InvalidMediaTypeValue` (which is a "body error")
- `MissingSchemaProperty` (in schema validation) gets propagated normally and is not considered as a body error

**Comment by p1c2u** [comment]
@domenkozar 
It filter out body errors because `validate_parameters` should return only parameters errors.

Of course `MissingSchemaProperty` should be caught too. Didn't notice it.

**Comment by domenkozar** [comment]
OK, I'll fix that. @p1c2u do you otherwise think this is good? I'd like to avoid PR long too open as it will often get into conflicts (as it already does).

**Comment by p1c2u** [comment]
LGTM. Can you resolve conflict and we can merge it.

**Pull request merged**
