### PR TITLE
Bugfix 311 falcon get media error

### LINKED ISSUE #311: Is openapi_core compatible with falcon 3.0.0?
I am getting the error while using openapi_core with falcon as middleware. All requests without body give error code 400 and following error message:
{'title': 'Invalid JSON', 'description': 'Could not parse an empty JSON body'}                                           
Looks like fixing the following code fixes this error:
https://github.com/p1c2u/openapi-core/blob/master/openapi_core/contrib/falcon/requests.py#26
        body = (                                                                                                        
            dumps(request.json) if getattr(request, "json", None)                                                       
-            else dumps(request.media)                                                                                    
+            else dumps(request.get_media({}))

### PR DESCRIPTION
**Pull request by BontaVlad**
Fixes #311. Makes openapi-core compatible with falcon 3.0.0

### CODE REVIEW

**Comment by BontaVlad** [comment]
Friendly reminder @p1c2u

**Review by p1c2u — APPROVED** [review]
Added minor changes and run tests against falcon3 LGTM

**Comment by p1c2u** [comment]
@BontaVlad thank you for the contribution

**Comment by BontaVlad** [comment]
@p1c2u thank you for all the hard work you put into maintaining this opensource project!

**Pull request merged**
